# Complete Framework
## Create the master data frame if it does not exist

In [1]:
import pandas as pd

file_path = "traj-partial.txt"

df = pd.read_csv(file_path, names=["name", "date", "quantity", "exposure", "tracked_id", "x", "y"], engine='python') 
df

        name         date quantity  exposure  tracked_id    x    y
0     balder  10032020-25       1u        30           4  170   52
1     balder  10032020-25       1u        30           4  170   51
2     balder  10032020-25       1u        30           4  172   50
3     balder  10032020-25       1u        30           4  170   50
4     balder  10032020-25       1u        30           4  170   49
...      ...          ...      ...       ...         ...  ...  ...
1507  balder  10032020-27       1u        30          30  285  162
1508  balder  10032020-27       1u        30          30  287  161
1509  balder  10032020-27       1u        30          30  289  161
1510  balder  10032020-27       1u        30          30  287  161
1511  balder  10032020-27       1u        30          30  288  159

[1512 rows x 7 columns]

In [2]:
traj_df = pd.DataFrame({"name":[], "date":[], "quantity":[], "exposure":[], "tracked_id":[], "traj":[]})

df1 = df.groupby('name')
for k1, v1 in df1:
    df2 = df1.get_group(k1)
    df3 = df2.groupby('date')
    for k3,v3 in df3:
        df4 = df3.get_group(k3)
        df5 = df4.groupby('quantity')
        for k5,v5 in df5:
            df6= df5.get_group(k5)
            df7 = df6.groupby('exposure') 
            for k7,v7 in df7:
                df8 = df7.get_group(k7)
                df9 = df8.groupby('tracked_id')
                for k9,v9 in df9:
                    df10 = df9.get_group(k9)
                    x = df10['x'].to_numpy()
                    y = df10['y'].to_numpy()
                    temp_df = pd.DataFrame({"name":[k1], "date":[k3], "quantity":[k5], "exposure":[k7], "tracked_id":[k9], "traj":[[x,y]]})
                    traj_df = pd.concat([temp_df, traj_df], ignore_index=True)

## Read the molity results file

In [8]:
mr_df = pd.read_csv("Motility_Results-partial.txt", engine='python') 
id_ = [x for x in range(mr_df.shape[0])]
mr_df["id"] = id_
mr_df

,ID1,ID2,ID3,ID4,VCL,VAP,VSL,LIN,STR,WOB,BeatCross,ALH,id
0,balder,10032020-25,1u,30,127.110054,56.666355,21.805430,0.171548,0.384804,0.445805,42.413790,4.761716,0
1,balder,10032020-25,1u,30,81.560410,28.683687,21.923042,0.268795,0.764304,0.351686,48.103447,2.787108,1
2,balder,10032020-25,1u,30,62.830067,34.478935,31.745853,0.505265,0.920732,0.548765,30.000000,2.864889,2
3,balder,10032020-25,1u,30,104.608300,62.548410,26.360271,0.251990,0.421438,0.597930,40.862070,4.427004,3
4,balder,10032020-25,1u,30,52.952248,18.416208,17.087137,0.322690,0.927831,0.347789,36.000000,2.450763,4
5,balder,10032020-25,1u,30,100.203200,38.645416,32.614815,0.325487,0.843950,0.385670,37.500000,3.464025,5
6,balder,10032020-25,1u,30,83.962270,58.365520,53.023500,0.631516,0.908473,0.695140,26.666666,4.724264,6
7,balder,10032020-25,1u,30,93.522050,55.739822,50.337696,0.538244,0.903083,0.596007,37.777780,4.632334,7
8,balder,10032020-25,1u,30,62.739914,26.312025,24.281622,0.387020,0.922834,0.419383,35.294117,2.329653,8
9,balder,10032020-26,1u,30,110.812650,63.909286,60.966790,0.550179,0.953958,0.576733,39.310345,5.016766,9
10,balder,10032020-26,1u,30,89.754295,59.842033,54.411648,0.606229,0.909255,0.666732,38.901100,3.735548,10
11,balder,10032020-26,1u,30,105.340300,60.351990,50.395550,0.478407,0.835027,0.572924,31.034483,4.321154,11
12,balder,10032020-26,1u,30,71.192990,34.888960,32.335860,0.454200,0.926822,0.490062,44.736843,2.999632,12
13,balder,10032020-26,1u,30,67.871220,43.028507,39.725380,0.585305,0.923234,0.633973,48.103447,3.072590,13
14,balder,10032020-26,1u,30,62.455692,34.035660,28.895557,0.462657,0.848979,0.544957,38.608696,2.308674,14

In [7]:
mr_df.shape

(15, 12)

## Sort the data frames

In [9]:
traj_df = traj_df.sort_values(by=['name', 'date', 'quantity', 'exposure', 'tracked_id'])

In [10]:
traj_df

,name,date,quantity,exposure,tracked_id,traj
16,balder,10032020-25,1u,30.0,4.0,"[[170, 170, 172, 170, 170, 172, 171, 172, 171,..."
15,balder,10032020-25,1u,30.0,19.0,"[[547, 547, 547, 547, 547, 547, 547, 547, 547,..."
14,balder,10032020-25,1u,30.0,26.0,"[[145, 145, 145, 145, 145, 146, 146, 147, 146,..."
13,balder,10032020-25,1u,30.0,30.0,"[[194, 195, 196, 195, 196, 196, 196, 197, 198,..."
12,balder,10032020-25,1u,30.0,45.0,"[[156, 156, 156, 157, 156, 156, 157, 157, 157,..."
11,balder,10032020-25,1u,30.0,52.0,"[[17, 17, 17, 17, 19, 18, 19, 19, 19, 19, 19, ..."
10,balder,10032020-25,1u,30.0,60.0,"[[544, 545, 546, 547, 547, 548, 548, 549, 549,..."
9,balder,10032020-25,1u,30.0,61.0,"[[567, 568, 567, 569, 569, 570, 570, 570, 571,..."
8,balder,10032020-25,1u,30.0,65.0,"[[147, 146, 147, 147, 147, 148, 147, 149, 148,..."
7,balder,10032020-26,1u,30.0,22.0,"[[325, 325, 326, 326, 327, 327, 328, 328, 328,..."
6,balder,10032020-26,1u,30.0,36.0,"[[23, 25, 24, 25, 25, 25, 25, 26, 25, 27, 26, ..."
5,balder,10032020-26,1u,30.0,41.0,"[[70, 70, 70, 71, 72, 72, 73, 73, 74, 74, 75, ..."
4,balder,10032020-26,1u,30.0,48.0,"[[421, 422, 421, 421, 421, 421, 421, 420, 421,..."
3,balder,10032020-26,1u,30.0,52.0,"[[133, 132, 132, 131, 131, 130, 129, 129, 128,..."
2,balder,10032020-26,1u,30.0,54.0,"[[228, 228, 228, 229, 229, 229, 229, 229, 229,..."
1,balder,10032020-26,1u,30.0,72.0,"[[463, 462, 461, 461, 460, 460, 458, 458, 458,..."
0,balder,10032020-27,1u,30.0,30.0,"[[255, 256, 256, 256, 257, 258, 259, 258, 261,..."

In [6]:
mr_df = mr_df.sort_values(by=['ID1', 'ID2', 'ID3', 'ID4', 'id'])

In [7]:
mr_df

,ID1,ID2,ID3,ID4,VCL,VAP,VSL,LIN,STR,WOB,BeatCross,ALH,id
6194,balder,01062021-25,0,0,79.959810,65.180660,60.576260,0.757584,0.929359,0.815168,30.000000,4.276645,6194
6195,balder,01062021-25,0,0,89.038410,47.606697,44.321228,0.497777,0.930987,0.534676,44.482758,3.3122602,6195
6196,balder,01062021-25,0,0,55.782050,39.061245,37.602840,0.674103,0.962664,0.700248,33.846153,2.2061138,6196
6197,balder,01062021-25,0,0,61.317635,50.661057,48.099777,0.784436,0.949443,0.826207,36.585365,3.6620018,6197
6198,balder,01062021-25,0,0,92.437790,31.140326,24.251595,0.262356,0.778784,0.336879,21.600000,2.8383772,6198
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3646,loki,10032020-9,0,0,96.704130,64.950470,59.788445,0.618262,0.920524,0.671641,26.470589,3.6918447,3646
3647,loki,10032020-9,0,0,120.385190,59.779380,54.945923,0.456418,0.919145,0.496568,28.000000,3.6505616,3647
3648,loki,10032020-9,0,0,58.640600,30.063608,27.091166,0.461986,0.901128,0.512676,23.571428,2.008077,3648
3649,loki,10032020-9,0,0,68.929520,18.630800,17.365812,0.251936,0.932102,0.270288,32.142857,2.827821,3649
3650,loki,10032020-9,0,0,57.033836,35.512478,33.005080,0.578693,0.929394,0.622656,23.076923,2.561492,3650

## Create the master data frame

In [8]:
traj_name_list = traj_df["name"].values.tolist()
traj_date_list = traj_df["date"].values.tolist()
traj_quantity_list = traj_df["quantity"].values.tolist()
traj_exposure_list = traj_df["exposure"].values.tolist()
traj_tracked_id_list = traj_df["tracked_id"].values.tolist()
traj_traj_list = traj_df["traj"].values.tolist()
mr_VCL_list = mr_df["VCL"].values.tolist()
mr_VAP_list = mr_df["VAP"].values.tolist()
mr_VSL_list = mr_df["VSL"].values.tolist()
mr_LIN_list = mr_df["LIN"].values.tolist()
mr_STR_list = mr_df["STR"].values.tolist()
mr_WOB_list = mr_df["WOB"].values.tolist()
mr_BeatCross_list = mr_df["BeatCross"].values.tolist()
mr_ALH_list = mr_df["ALH"].values.tolist()

In [9]:
master_dict = {"name":traj_name_list, "date":traj_date_list, "quantity":traj_quantity_list, 
               "exposure":traj_exposure_list, "tracked_id":traj_tracked_id_list, "traj":traj_traj_list,
              "VCL":mr_VCL_list, "VAP":mr_VAP_list, "VSL":mr_VSL_list, "LIN":mr_LIN_list, "STR":mr_STR_list,
              "WOB":mr_WOB_list, "BeatCross":mr_BeatCross_list, "ALH":mr_ALH_list}

In [10]:
master_df = pd.DataFrame(master_dict)

In [11]:
master_df

,name,date,quantity,exposure,tracked_id,traj,VCL,VAP,VSL,LIN,STR,WOB,BeatCross,ALH
0,balder,01062021-25,0,0.0,1.0,"[[69, 70, 71, 71, 72, 73, 73, 74, 75, 76, 76, ...",79.959810,65.180660,60.576260,0.757584,0.929359,0.815168,30.000000,4.276645
1,balder,01062021-25,0,0.0,3.0,"[[209, 208, 210, 210, 211, 212, 212, 214, 214,...",89.038410,47.606697,44.321228,0.497777,0.930987,0.534676,44.482758,3.3122602
2,balder,01062021-25,0,0.0,4.0,"[[166, 166, 166, 166, 166, 166, 165, 165, 164,...",55.782050,39.061245,37.602840,0.674103,0.962664,0.700248,33.846153,2.2061138
3,balder,01062021-25,0,0.0,6.0,"[[153, 152, 151, 151, 150, 149, 149, 149, 148,...",61.317635,50.661057,48.099777,0.784436,0.949443,0.826207,36.585365,3.6620018
4,balder,01062021-25,0,0.0,7.0,"[[101, 100, 100, 100, 100, 92, 91, 91, 92, 91,...",92.437790,31.140326,24.251595,0.262356,0.778784,0.336879,21.600000,2.8383772
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20800,loki,10032020-9,0,0.0,287.0,"[[1, 2, 3, 4, 4, 6, 7, 8, 8, 10, 11, 12, 12, 1...",96.704130,64.950470,59.788445,0.618262,0.920524,0.671641,26.470589,3.6918447
20801,loki,10032020-9,0,0.0,290.0,"[[407, 406, 407, 404, 403, 402, 401, 401, 401,...",120.385190,59.779380,54.945923,0.456418,0.919145,0.496568,28.000000,3.6505616
20802,loki,10032020-9,0,0.0,291.0,"[[200, 201, 200, 202, 202, 202, 203, 203, 203,...",58.640600,30.063608,27.091166,0.461986,0.901128,0.512676,23.571428,2.008077
20803,loki,10032020-9,0,0.0,293.0,"[[182, 181, 181, 180, 181, 181, 180, 181, 180,...",68.929520,18.630800,17.365812,0.251936,0.932102,0.270288,32.142857,2.827821
20804,loki,10032020-9,0,0.0,295.0,"[[270, 271, 271, 271, 272, 272, 272, 272, 273,...",57.033836,35.512478,33.005080,0.578693,0.929394,0.622656,23.076923,2.561492

In [12]:
master_df.to_pickle("master_06052022.pkl")

## Load the master data frame if it already exists

In [ ]:
master_df = pd.read_pickle("master_06052022.pkl")

## Group the master data frame according to its exposure time

In [13]:
master0_df = master_df[master_df["exposure"] == 0.0]
master0_df

,name,date,quantity,exposure,tracked_id,traj,VCL,VAP,VSL,LIN,STR,WOB,BeatCross,ALH
0,balder,01062021-25,0,0.0,1.0,"[[69, 70, 71, 71, 72, 73, 73, 74, 75, 76, 76, ...",79.959810,65.180660,60.576260,0.757584,0.929359,0.815168,30.000000,4.276645
1,balder,01062021-25,0,0.0,3.0,"[[209, 208, 210, 210, 211, 212, 212, 214, 214,...",89.038410,47.606697,44.321228,0.497777,0.930987,0.534676,44.482758,3.3122602
2,balder,01062021-25,0,0.0,4.0,"[[166, 166, 166, 166, 166, 166, 165, 165, 164,...",55.782050,39.061245,37.602840,0.674103,0.962664,0.700248,33.846153,2.2061138
3,balder,01062021-25,0,0.0,6.0,"[[153, 152, 151, 151, 150, 149, 149, 149, 148,...",61.317635,50.661057,48.099777,0.784436,0.949443,0.826207,36.585365,3.6620018
4,balder,01062021-25,0,0.0,7.0,"[[101, 100, 100, 100, 100, 92, 91, 91, 92, 91,...",92.437790,31.140326,24.251595,0.262356,0.778784,0.336879,21.600000,2.8383772
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20800,loki,10032020-9,0,0.0,287.0,"[[1, 2, 3, 4, 4, 6, 7, 8, 8, 10, 11, 12, 12, 1...",96.704130,64.950470,59.788445,0.618262,0.920524,0.671641,26.470589,3.6918447
20801,loki,10032020-9,0,0.0,290.0,"[[407, 406, 407, 404, 403, 402, 401, 401, 401,...",120.385190,59.779380,54.945923,0.456418,0.919145,0.496568,28.000000,3.6505616
20802,loki,10032020-9,0,0.0,291.0,"[[200, 201, 200, 202, 202, 202, 203, 203, 203,...",58.640600,30.063608,27.091166,0.461986,0.901128,0.512676,23.571428,2.008077
20803,loki,10032020-9,0,0.0,293.0,"[[182, 181, 181, 180, 181, 181, 180, 181, 180,...",68.929520,18.630800,17.365812,0.251936,0.932102,0.270288,32.142857,2.827821
20804,loki,10032020-9,0,0.0,295.0,"[[270, 271, 271, 271, 272, 272, 272, 272, 273,...",57.033836,35.512478,33.005080,0.578693,0.929394,0.622656,23.076923,2.561492

In [14]:
master30_df = master_df[master_df["exposure"] == 30.0]
master30_df

,name,date,quantity,exposure,tracked_id,traj,VCL,VAP,VSL,LIN,STR,WOB,BeatCross,ALH
1827,balder,01062021-53,0,30.0,3.0,"[[127, 126, 124, 124, 123, 122, 121, 119, 119,...",108.312470,74.082260,46.349052,0.427920,0.625643,0.683968,38.028168,5.5832863
1828,balder,01062021-53,0,30.0,5.0,"[[239, 239, 238, 238, 237, 237, 237, 236, 236,...",60.646740,47.829323,45.181210,0.744990,0.944634,0.788654,34.736843,3.4490652
1829,balder,01062021-53,0,30.0,6.0,"[[542, 543, 544, 544, 544, 545, 546, 546, 547,...",57.764587,43.893170,35.392400,0.612701,0.806330,0.759863,33.620690,2.7962613
1830,balder,01062021-53,0,30.0,7.0,"[[522, 523, 524, 525, 526, 526, 528, 528, 529,...",86.560760,64.950830,61.770550,0.713609,0.951036,0.750350,26.470589,4.2372675
1831,balder,01062021-53,0,30.0,9.0,"[[235, 235, 235, 234, 235, 234, 235, 234, 235,...",64.978580,24.099330,23.088003,0.355317,0.958035,0.370881,45.365852,2.662408
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20556,loki,10032020-57,10n,30.0,346.0,"[[85, 85, 85, 84, 86, 86, 84, 86, 85, 85, 86, ...",83.296180,25.878532,20.373423,0.244590,0.787271,0.310681,31.764706,3.910884
20557,loki,10032020-57,10n,30.0,353.0,"[[14, 15, 13, 14, 12, 13, 12, 11, 12, 11, 13, ...",111.311910,40.428207,36.676050,0.329489,0.907190,0.363197,36.428570,4.0320015
20558,loki,10032020-57,10n,30.0,354.0,"[[106, 106, 107, 108, 107, 108, 108, 109, 109,...",55.782700,15.695491,11.479502,0.205790,0.731388,0.281368,24.444445,1.4891511
20559,loki,10032020-57,10n,30.0,355.0,"[[176, 176, 177, 177, 178, 179, 179, 180, 180,...",53.996098,32.559372,28.221498,0.522658,0.866770,0.602995,18.461538,1.5293857
20560,loki,10032020-57,10n,30.0,357.0,"[[152, 152, 151, 152, 151, 152, 151, 152, 152,...",60.158386,33.464756,32.175728,0.534850,0.961481,0.556277,27.692308,2.0966282

# Generate the images
## Warning: run this section only once

In [25]:
traj0_list = master0_df['traj'].values.tolist()
traj30_list = master30_df['traj'].values.tolist()

In [26]:
import numpy as np

def center_of_traj(x, y):
    max_x = np.amax(x)
    min_x = np.amin(x)
    max_y = np.amax(y)
    min_y = np.amin(y)
    x_c = np.mean([max_x, min_x])
    y_c = np.mean([max_y, min_y])
    return x_c, y_c

In [27]:
import matplotlib.pyplot as plt
from PIL import Image
from tqdm import tqdm
import numpy as np

window_size = 60
for index, traj in tqdm(enumerate(traj0_list)):
    list_x, list_y = zip(traj)
    x = np.asarray(list_x).squeeze()
    y = np.asarray(list_y).squeeze()
    c = range(len(x)) #arange numpy
    x_c, y_c = center_of_traj(x, y)
    plt.figure(figsize=[2,2])
    plt.plot(x, y, 'k')
    plt.xlim([x_c - window_size/2, x_c + window_size/2])
    plt.ylim([y_c - window_size/2, y_c + window_size/2])
    plt.gca().set_aspect('equal', adjustable='box')
    plt.axis('off')
    new_id = '{:05d}'.format(index)
    plt.savefig(f'img_0_05052022/{new_id}.png')
    plt.close()
    
for index, traj in tqdm(enumerate(traj30_list)):
    list_x, list_y = zip(traj)
    x = np.asarray(list_x).squeeze()
    y = np.asarray(list_y).squeeze()
    c = range(len(x)) #arange numpy
    x_c, y_c = center_of_traj(x, y)
    plt.figure(figsize=[2,2])
    plt.plot(x, y, 'k')
    plt.xlim([x_c - window_size/2, x_c + window_size/2])
    plt.ylim([y_c - window_size/2, y_c + window_size/2])
    plt.gca().set_aspect('equal', adjustable='box')
    plt.axis('off')
    new_id = '{:05d}'.format(index)
    plt.savefig(f'img_30_05052022/{new_id}.png')
    plt.close()

11394it [02:07, 89.04it/s]
9411it [01:51, 84.78it/s]

# Load the images

In [35]:
import pathlib

traj0_img_list =  sorted(str(p) for p in pathlib.Path("img_0_05052022/").glob("*.png"))
traj30_img_list =  sorted(str(p) for p in pathlib.Path("img_30_05052022/").glob("*.png"))

print(len(traj0_img_list))
print(len(traj30_img_list))

11394
9411

In [36]:
import numpy as np
from PIL import Image
from numpy import asarray

list0_arrays = []
for elem in traj0_img_list:
    img = Image.open(elem).convert('L')
    numpydata = asarray(img).flatten()
    list0_arrays.append(numpydata)
    
train0_np = np.asarray(list0_arrays)
train0_tensor = train0_np/255

list30_arrays = []
for elem in traj30_img_list:
    img = Image.open(elem).convert('L')
    numpydata = asarray(img).flatten()
    list30_arrays.append(numpydata)
    
train30_np = np.asarray(list30_arrays)
train30_tensor = train30_np/255

## Generate the labels

In [31]:
from sklearn.cluster import DBSCAN

clustering0 = DBSCAN(eps=0.5, min_samples=2).fit(train0_tensor)
y0_labels = clustering0.labels_
n0_clusters = np.amax(y0_labels)

print(y0_labels)
print(n0_clusters)

[-1 -1 -1 ... -1 -1 -1]
36

In [32]:
clustering30 = DBSCAN(eps=0.5, min_samples=2).fit(train30_tensor)
y30_labels = clustering30.labels_
n30_clusters = np.amax(y30_labels)

print(y30_labels)
print(n30_clusters)

[-1 -1 -1 ... -1 -1 -1]
-1

In [33]:
master0_df['cluster'] = y0_labels
master30_df['cluster'] = y30_labels

/tmp/ipykernel_11891/1637004461.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  master0_df['cluster'] = y0_labels
/tmp/ipykernel_11891/1637004461.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  master30_df['cluster'] = y30_labels

In [34]:
master0_df.to_pickle("master0_05052022.pkl")
master30_df.to_pickle("master30_05052022.pkl")

## Load the data frames if they are not stored in the memory

In [1]:
import pandas as pd
master0_df = pd.read_pickle("master0_05052022.pkl")
master30_df = pd.read_pickle("master30_05052022.pkl")

In [2]:
master0_df

,name,date,quantity,exposure,tracked_id,traj,VCL,VAP,VSL,LIN,STR,WOB,BeatCross,ALH,cluster
0,balder,01062021-25,0,0.0,1.0,"[[69, 70, 71, 71, 72, 73, 73, 74, 75, 76, 76, ...",79.959810,65.180660,60.576260,0.757584,0.929359,0.815168,30.000000,4.276645,5
1,balder,01062021-25,0,0.0,3.0,"[[209, 208, 210, 210, 211, 212, 212, 214, 214,...",89.038410,47.606697,44.321228,0.497777,0.930987,0.534676,44.482758,3.3122602,5
2,balder,01062021-25,0,0.0,4.0,"[[166, 166, 166, 166, 166, 166, 165, 165, 164,...",55.782050,39.061245,37.602840,0.674103,0.962664,0.700248,33.846153,2.2061138,1
3,balder,01062021-25,0,0.0,6.0,"[[153, 152, 151, 151, 150, 149, 149, 149, 148,...",61.317635,50.661057,48.099777,0.784436,0.949443,0.826207,36.585365,3.6620018,3
4,balder,01062021-25,0,0.0,7.0,"[[101, 100, 100, 100, 100, 92, 91, 91, 92, 91,...",92.437790,31.140326,24.251595,0.262356,0.778784,0.336879,21.600000,2.8383772,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20800,loki,10032020-9,0,0.0,287.0,"[[1, 2, 3, 4, 4, 6, 7, 8, 8, 10, 11, 12, 12, 1...",96.704130,64.950470,59.788445,0.618262,0.920524,0.671641,26.470589,3.6918447,1
20801,loki,10032020-9,0,0.0,290.0,"[[407, 406, 407, 404, 403, 402, 401, 401, 401,...",120.385190,59.779380,54.945923,0.456418,0.919145,0.496568,28.000000,3.6505616,1
20802,loki,10032020-9,0,0.0,291.0,"[[200, 201, 200, 202, 202, 202, 203, 203, 203,...",58.640600,30.063608,27.091166,0.461986,0.901128,0.512676,23.571428,2.008077,5
20803,loki,10032020-9,0,0.0,293.0,"[[182, 181, 181, 180, 181, 181, 180, 181, 180,...",68.929520,18.630800,17.365812,0.251936,0.932102,0.270288,32.142857,2.827821,5
20804,loki,10032020-9,0,0.0,295.0,"[[270, 271, 271, 271, 272, 272, 272, 272, 273,...",57.033836,35.512478,33.005080,0.578693,0.929394,0.622656,23.076923,2.561492,1

In [3]:
master30_df

,name,date,quantity,exposure,tracked_id,traj,VCL,VAP,VSL,LIN,STR,WOB,BeatCross,ALH,cluster
1827,balder,01062021-53,0,30.0,3.0,"[[127, 126, 124, 124, 123, 122, 121, 119, 119,...",108.312470,74.082260,46.349052,0.427920,0.625643,0.683968,38.028168,5.5832863,2
1828,balder,01062021-53,0,30.0,5.0,"[[239, 239, 238, 238, 237, 237, 237, 236, 236,...",60.646740,47.829323,45.181210,0.744990,0.944634,0.788654,34.736843,3.4490652,5
1829,balder,01062021-53,0,30.0,6.0,"[[542, 543, 544, 544, 544, 545, 546, 546, 547,...",57.764587,43.893170,35.392400,0.612701,0.806330,0.759863,33.620690,2.7962613,4
1830,balder,01062021-53,0,30.0,7.0,"[[522, 523, 524, 525, 526, 526, 528, 528, 529,...",86.560760,64.950830,61.770550,0.713609,0.951036,0.750350,26.470589,4.2372675,0
1831,balder,01062021-53,0,30.0,9.0,"[[235, 235, 235, 234, 235, 234, 235, 234, 235,...",64.978580,24.099330,23.088003,0.355317,0.958035,0.370881,45.365852,2.662408,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20556,loki,10032020-57,10n,30.0,346.0,"[[85, 85, 85, 84, 86, 86, 84, 86, 85, 85, 86, ...",83.296180,25.878532,20.373423,0.244590,0.787271,0.310681,31.764706,3.910884,0
20557,loki,10032020-57,10n,30.0,353.0,"[[14, 15, 13, 14, 12, 13, 12, 11, 12, 11, 13, ...",111.311910,40.428207,36.676050,0.329489,0.907190,0.363197,36.428570,4.0320015,3
20558,loki,10032020-57,10n,30.0,354.0,"[[106, 106, 107, 108, 107, 108, 108, 109, 109,...",55.782700,15.695491,11.479502,0.205790,0.731388,0.281368,24.444445,1.4891511,0
20559,loki,10032020-57,10n,30.0,355.0,"[[176, 176, 177, 177, 178, 179, 179, 180, 180,...",53.996098,32.559372,28.221498,0.522658,0.866770,0.602995,18.461538,1.5293857,0
20560,loki,10032020-57,10n,30.0,357.0,"[[152, 152, 151, 152, 151, 152, 151, 152, 152,...",60.158386,33.464756,32.175728,0.534850,0.961481,0.556277,27.692308,2.0966282,3

## Generate the subplots if they are not already generated

In [36]:
cluster0_0 = master0_df[master0_df["cluster"]==0]
cluster0_1 = master0_df[master0_df["cluster"]==1]
cluster0_2 = master0_df[master0_df["cluster"]==2]
cluster0_3 = master0_df[master0_df["cluster"]==3]
cluster0_4 = master0_df[master0_df["cluster"]==4]
cluster0_5 = master0_df[master0_df["cluster"]==5]

cluster30_0 = master30_df[master30_df["cluster"]==0]
cluster30_1 = master30_df[master30_df["cluster"]==1]
cluster30_2 = master30_df[master30_df["cluster"]==2]
cluster30_3 = master30_df[master30_df["cluster"]==3]
cluster30_4 = master30_df[master30_df["cluster"]==4]
cluster30_5 = master30_df[master30_df["cluster"]==5]

In [37]:
# TODO: "continue-for" if the last element is reached
def subplot_gen(cluster_df, n_row, n_col, n_fig, path, train_np):
    
    i_c = cluster_df.index.values.astype(int)
    count_c = 0
    l_c = len(cluster_df)
    
    for i in range(n_fig):
        fig, axs = plt.subplots(n_col, n_row, figsize=(25,25), constrained_layout=True,
                        sharex=True, sharey=True)#,sharex='col', sharey='row')
        plt.figure(figsize=(5,5), dpi= 100, facecolor='w', edgecolor='k')
        plt.rcParams['figure.figsize'] = [16, 24]
        plt.rcParams['figure.dpi'] = 100 # 200 e.g. is really fine, but slower
        plt.tight_layout(pad=0.01, w_pad=0, h_pad=0)

        for k in range(n_row):
            for j in range(n_col):
                if count_c < l_c:
                    axs[j, k].imshow(train_np[i_c[count_c]].reshape(144,144),cmap='gray', interpolation='nearest')
                    axs[j, k].axis('off')
                    count_c += 1

        plt.close() #try to remove this
        path_filename = path+str(i)+".png"
        plt.savefig(path_filename)
        plt.close("all")
    
    return

In [42]:
print(len(cluster0_0))
print(len(cluster0_1))
print(len(cluster0_2))
print(len(cluster0_3))
print(len(cluster0_4))
print(len(cluster0_5))

print(len(cluster30_0))
print(len(cluster30_1))
print(len(cluster30_2))
print(len(cluster30_3))
print(len(cluster30_4))
print(len(cluster30_5))

3039
1878
1555
2256
577
2089
2228
1165
1863
1516
1136
1503

In [43]:
from matplotlib import pyplot as plt

n_fig = 10
n_row = 3
n_col = 3

path0_0 = "c0_6/0/"
path0_1 = "c0_6/1/"
path0_2 = "c0_6/2/"
path0_3 = "c0_6/3/"
path0_4 = "c0_6/4/"
path0_5 = "c0_6/5/"

subplot_gen(cluster0_0, n_row, n_col, n_fig, path0_0, train0_np)
subplot_gen(cluster0_1, n_row, n_col, n_fig, path0_1, train0_np)
subplot_gen(cluster0_2, n_row, n_col, n_fig, path0_2, train0_np)
subplot_gen(cluster0_3, n_row, n_col, n_fig, path0_3, train0_np)
subplot_gen(cluster0_4, n_row, n_col, n_fig, path0_4, train0_np)
subplot_gen(cluster0_5, n_row, n_col, n_fig, path0_5, train0_np)

path30_0 = "c30_6/0/"
path30_1 = "c30_6/1/"
path30_2 = "c30_6/2/"
path30_3 = "c30_6/3/"
path30_4 = "c30_6/4/"
path30_5 = "c30_6/5/"

subplot_gen(cluster30_0, n_row, n_col, n_fig, path30_0, train30_np)
subplot_gen(cluster30_1, n_row, n_col, n_fig, path30_1, train30_np)
subplot_gen(cluster30_2, n_row, n_col, n_fig, path30_2, train30_np)
subplot_gen(cluster30_3, n_row, n_col, n_fig, path30_3, train30_np)
subplot_gen(cluster30_4, n_row, n_col, n_fig, path30_4, train30_np)
subplot_gen(cluster30_5, n_row, n_col, n_fig, path30_5, train30_np)

## Statistics

In [12]:
import numpy as np
n_clusters = 6
clusters_array = np.arange(n_clusters)
quantity = ["0", "10n", "100n", "1u"]

cluster0_list = []
labels0_list = []
for c in clusters_array:
    cluster_i = master0_df[master0_df["cluster"]==c]
    for q in quantity:
        cluster_j = cluster_i[cluster_i["quantity"]==q]
        cluster0_list.append(cluster_j)
        labels = [str(c), q]
        labels0_list.append(labels)

cluster30_list = []
labels30_list = []
for c in clusters_array:
    cluster_i = master30_df[master30_df["cluster"]==c]
    for q in quantity:
        cluster_j = cluster_i[cluster_i["quantity"]==q]
        cluster30_list.append(cluster_j)
        labels = [str(c), q]
        labels30_list.append(labels)

In [13]:
print("exposure: 0")
for id_, elem in enumerate(cluster0_list):
    elem_mean = elem.mean()
    print(labels0_list[id_])
    print("mean\n" , elem_mean)
    elem_std = elem.std()
    print("std\n", elem_std)

exposure: 0
['0', '0']
mean
 exposure        0.000000
tracked_id    115.167038
VCL            98.226440
VAP            56.295314
VSL            38.854403
LIN             0.411570
STR             0.697498
WOB             0.582793
BeatCross      38.904154
cluster         0.000000
dtype: float64
std
 exposure       0.000000
tracked_id    91.686459
VCL           30.623901
VAP           16.429454
VSL           15.844317
LIN            0.150159
STR            0.194417
WOB            0.101980
BeatCross      4.685612
cluster        0.000000
dtype: float64
['0', '10n']
mean
 exposure        0.000000
tracked_id    112.292651
VCL           105.934811
VAP            59.236676
VSL            39.556037
LIN             0.395163
STR             0.679287
WOB             0.573399
BeatCross      38.556770
cluster         0.000000
dtype: float64
std
 exposure       0.000000
tracked_id    83.946918
VCL           38.109677
VAP           19.050827
VSL           17.273528
LIN            0.153477
STR            0.202529
WOB            0.102071
BeatCross      5.110871
cluster        0.000000
dtype: float64
['0', '100n']
mean
 exposure        0.000000
tracked_id     97.309064
VCL           102.856223
VAP            56.368967
VSL            37.349372
LIN             0.387115
STR             0.679466
WOB             0.562843
BeatCross      39.390306
cluster         0.000000
dtype: float64
std
 exposure       0.000000
tracked_id    71.718528
VCL           39.770338
VAP           19.514248
VSL           16.246415
LIN            0.149092
STR            0.200201
WOB            0.104803
BeatCross      4.467186
cluster        0.000000
dtype: float64
['0', '1u']
mean
 exposure        0.000000
tracked_id    120.035411
VCL           117.371597
VAP            64.550787
VSL            42.553065
LIN             0.393860
STR             0.672116
WOB             0.568030
BeatCross      38.741570
cluster         0.000000
dtype: float64
std
 exposure       0.000000
tracked_id    86.859650
VCL           45.737489
VAP           21.994265
VSL           19.079264
LIN            0.180795
STR            0.216784
WOB            0.120287
BeatCross      4.843896
cluster        0.000000
dtype: float64
['1', '0']
mean
 exposure        0.000000
tracked_id    228.640693
VCL            80.119019
VAP            40.254040
VSL            35.452515
LIN             0.443441
STR             0.867549
WOB             0.501280
BeatCross      34.554225
cluster         1.000000
dtype: float64
std
 exposure        0.000000
tracked_id    166.342513
VCL            23.138076
VAP            17.411157
VSL            17.304199
LIN             0.169611
STR             0.125728
WOB             0.154162
BeatCross       6.746131
cluster         0.000000
dtype: float64
['1', '10n']
mean
 exposure        0.000000
tracked_id    157.326203
VCL            84.313557
VAP            42.353568
VSL            36.987235
LIN             0.443851
STR             0.860766
WOB             0.505640
BeatCross      34.918104
cluster         1.000000
dtype: float64
std
 exposure        0.000000
tracked_id    113.854502
VCL            31.368293
VAP            19.255847
VSL            18.561176
LIN             0.160010
STR             0.123633
WOB             0.144689
BeatCross       6.435060
cluster         0.000000
dtype: float64
['1', '100n']
mean
 exposure        0.000000
tracked_id    135.514512
VCL            79.835468
VAP            38.780803
VSL            34.275595
LIN             0.430980
STR             0.871474
WOB             0.485680
BeatCross      36.810734
cluster         1.000000
dtype: float64
std
 exposure       0.000000
tracked_id    90.981199
VCL           27.949089
VAP           17.764913
VSL           17.493792
LIN            0.158872
STR            0.122862
WOB            0.144326
BeatCross      6.575350
cluster        0.000000
dtype: float64
['1', '1u']
mean
 exposure        0.000000
tracked_id    172.386574
VCL            90.638803
VAP            47.238703
VSL            42.209180
LIN             0.469968
STR             0.877540
WOB             0.523421
BeatCross      35.112171
cluster         1.000000
dtype: float64
std
 exposure        0.000000
tracked_id    117.075089
VCL            29.980721
VAP            20.713748
VSL            20.664927
LIN             0.182260
STR             0.119996
WOB             0.166049
BeatCross       6.273055
cluster         0.000000
dtype: float64
['2', '0']
mean
 exposure        0.000000
tracked_id    184.098182
VCL            86.463131
VAP            45.695050
VSL            38.910192
LIN             0.457913
STR             0.841802
WOB             0.534227
BeatCross      36.123804
cluster         2.000000
dtype: float64
std
 exposure        0.000000
tracked_id    141.694447
VCL            26.676194
VAP            15.809350
VSL            16.242448
LIN             0.158567
STR             0.144267
WOB             0.132240
BeatCross       6.356727
cluster         0.000000
dtype: float64
['2', '10n']
mean
 exposure        0.000000
tracked_id    136.886567
VCL            88.468602
VAP            45.986386
VSL            39.101729
LIN             0.449143
STR             0.835392
WOB             0.526407
BeatCross      36.699122
cluster         2.000000
dtype: float64
std
 exposure        0.000000
tracked_id    104.962036
VCL            32.679383
VAP            18.479636
VSL            18.307787
LIN             0.160753
STR             0.141544
WOB             0.136448
BeatCross       6.510806
cluster         0.000000
dtype: float64
['2', '100n']
mean
 exposure        0.000000
tracked_id    115.079755
VCL            88.421876
VAP            44.510086
VSL            38.377064
LIN             0.443329
STR             0.855283
WOB             0.509003
BeatCross      37.431746
cluster         2.000000
dtype: float64
std
 exposure       0.000000
tracked_id    82.105484
VCL           35.443521
VAP           19.192410
VSL           18.087585
LIN            0.150767
STR            0.126676
WOB            0.129248
BeatCross      6.341907
cluster        0.000000
dtype: float64
['2', '1u']
mean
 exposure        0.000000
tracked_id    151.232558
VCL           101.598825
VAP            52.397428
VSL            43.285377
LIN             0.443114
STR             0.814898
WOB             0.528756
BeatCross      35.628988
cluster         2.000000
dtype: float64
std
 exposure        0.000000
tracked_id    108.370510
VCL            39.633678
VAP            20.642460
VSL            20.653455
LIN             0.174266
STR             0.167225
WOB             0.138564
BeatCross       6.497074
cluster         0.000000
dtype: float64
['3', '0']
mean
 exposure        0.000000
tracked_id    241.050725
VCL            77.829197
VAP            37.278041
VSL            32.850530
LIN             0.422773
STR             0.866871
WOB             0.478167
BeatCross      34.457885
cluster         3.000000
dtype: float64
std
 exposure        0.000000
tracked_id    170.956820
VCL            22.761217
VAP            16.491663
VSL            16.386719
LIN             0.167696
STR             0.118657
WOB             0.155211
BeatCross       7.022529
cluster         0.000000
dtype: float64
['3', '10n']
mean
 exposure        0.000000
tracked_id    170.406522
VCL            79.746281
VAP            40.280194
VSL            35.492818
LIN             0.449281
STR             0.865830
WOB             0.506695
BeatCross      34.649490
cluster         3.000000
dtype: float64
std
 exposure        0.000000
tracked_id    108.955158
VCL            27.824549
VAP            18.942390
VSL            18.691875
LIN             0.185191
STR             0.130404
WOB             0.168899
BeatCross       6.898466
cluster         0.000000
dtype: float64
['3', '100n']
mean
 exposure        0.000000
tracked_id    146.924612
VCL            81.035610
VAP            39.300863
VSL            35.104342
LIN             0.435761
STR             0.875761
WOB             0.486066
BeatCross      34.910553
cluster         3.000000
dtype: float64
std
 exposure       0.000000
tracked_id    97.225779
VCL           27.286647
VAP           18.888803
VSL           18.478259
LIN            0.182981
STR            0.106715
WOB            0.171837
BeatCross      7.244163
cluster        0.000000
dtype: float64
['3', '1u']
mean
 exposure        0.000000
tracked_id    178.626692
VCL            89.069771
VAP            44.018739
VSL            38.647409
LIN             0.446182
STR             0.861923
WOB             0.503395
BeatCross      34.391210
cluster         3.000000
dtype: float64
std
 exposure        0.000000
tracked_id    118.783620
VCL            33.274174
VAP            20.152482
VSL            19.986681
LIN             0.194997
STR             0.133454
WOB             0.178522
BeatCross       6.877134
cluster         0.000000
dtype: float64
['4', '0']
mean
 exposure        0.000000
tracked_id     93.862275
VCL           103.068375
VAP            50.164758
VSL            21.510544
LIN             0.214562
STR             0.432269
WOB             0.497606
BeatCross      38.826216
cluster         4.000000
dtype: float64
std
 exposure       0.000000
tracked_id    75.560150
VCL           30.933198
VAP           13.133414
VSL           10.721904
LIN            0.102025
STR            0.174123
WOB            0.089967
BeatCross      4.735665
cluster        0.000000
dtype: float64

['4', '10n']
mean
 exposure        0.000000
tracked_id    122.182692
VCL           125.887254
VAP            58.376246
VSL            24.069830
LIN             0.205748
STR             0.429220
WOB             0.478847
BeatCross      37.980697
cluster         4.000000
dtype: float64
std
 exposure       0.000000
tracked_id    99.421019
VCL           46.878945
VAP           19.117228
VSL           11.549878
LIN            0.104216
STR            0.177065
WOB            0.098621
BeatCross      4.453888
cluster        0.000000
dtype: float64
['4', '100n']
mean
 exposure        0.000000
tracked_id     86.535714
VCL           115.690082
VAP            55.239883
VSL            20.921188
LIN             0.190088
STR             0.403482
WOB             0.491646
BeatCross      39.206012
cluster         4.000000
dtype: float64
std
 exposure       0.000000
tracked_id    68.266559
VCL           48.186506
VAP           20.909825
VSL           10.446431
LIN            0.079762
STR            0.176780
WOB            0.105610
BeatCross      4.363011
cluster        0.000000
dtype: float64
['4', '1u']
mean
 exposure        0.000000
tracked_id     98.757732
VCL           128.848459
VAP            59.452933
VSL            23.486217
LIN             0.188621
STR             0.403127
WOB             0.474444
BeatCross      38.597113
cluster         4.000000
dtype: float64
std
 exposure       0.000000
tracked_id    66.756212
VCL           46.913077
VAP           19.329167
VSL           12.857532
LIN            0.085545
STR            0.167277
WOB            0.092372
BeatCross      5.151855
cluster        0.000000
dtype: float64
['5', '0']
mean
 exposure        0.000000
tracked_id    243.521792
VCL            81.160813
VAP            37.281389
VSL            32.190800
LIN             0.397262
STR             0.850446
WOB             0.458722
BeatCross      34.776787
cluster         5.000000
dtype: float64
std
 exposure        0.000000
tracked_id    177.641314
VCL            24.862053
VAP            16.594932
VSL            16.266455
LIN             0.158369
STR             0.121419
WOB             0.148878
BeatCross       6.789749
cluster         0.000000
dtype: float64
['5', '10n']
mean
 exposure        0.000000
tracked_id    152.109557
VCL            81.578250
VAP            40.150611
VSL            34.941680
LIN             0.438812
STR             0.855994
WOB             0.500179
BeatCross      34.316328
cluster         5.000000
dtype: float64
std
 exposure        0.000000
tracked_id    110.445760
VCL            29.183278
VAP            18.432192
VSL            18.188137
LIN             0.186842
STR             0.132984
WOB             0.171998
BeatCross       6.933246
cluster         0.000000
dtype: float64
['5', '100n']
mean
 exposure        0.000000
tracked_id    141.000000
VCL            79.585459
VAP            38.483195
VSL            34.094206
LIN             0.422709
STR             0.871479
WOB             0.477626
BeatCross      36.590197
cluster         5.000000
dtype: float64
std
 exposure       0.000000
tracked_id    94.955063
VCL           30.067466
VAP           19.753450
VSL           19.143458
LIN            0.151876
STR            0.118609
WOB            0.139381
BeatCross      6.672401
cluster        0.000000
dtype: float64
['5', '1u']
mean
 exposure        0.000000
tracked_id    180.585153
VCL            86.607545
VAP            44.558718
VSL            39.311516
LIN             0.456104
STR             0.860442
WOB             0.515439
BeatCross      34.253512
cluster         5.000000
dtype: float64
std
 exposure        0.000000
tracked_id    121.224597
VCL            28.958458
VAP            20.329262
VSL            20.307952
LIN             0.190247
STR             0.130849
WOB             0.172849
BeatCross       6.752000
cluster         0.000000
dtype: float64

In [14]:
print("exposure: 30")
for id_, elem in enumerate(cluster30_list):
    elem_mean = elem.mean()
    print(labels30_list[id_])
    print("mean\n" , elem_mean)
    elem_std = elem.std()
    print("std\n", elem_std)

exposure: 30
['0', '0']
mean
 exposure       30.000000
tracked_id    149.732331
VCL            79.400800
VAP            43.691334
VSL            39.760837
LIN             0.496670
STR             0.893931
WOB             0.546417
BeatCross      35.306378
cluster         0.000000
dtype: float64
std
 exposure        0.000000
tracked_id    105.971413
VCL            24.069514
VAP            19.121373
VSL            19.092950
LIN             0.173974
STR             0.102127
WOB             0.160922
BeatCross       6.761444
cluster         0.000000
dtype: float64
['0', '10n']
mean
 exposure       30.000000
tracked_id    132.879771
VCL            75.051307
VAP            39.899910
VSL            36.125106
LIN             0.476958
STR             0.895326
WOB             0.526222
BeatCross      35.865841
cluster         0.000000
dtype: float64
std
 exposure       0.000000
tracked_id    94.261317
VCL           24.934582
VAP           18.246351
VSL           17.938371
LIN            0.158476
STR            0.098244
WOB            0.146977
BeatCross      6.746481
cluster        0.000000
dtype: float64
['0', '100n']
mean
 exposure       30.000000
tracked_id    108.542411
VCL            77.171233
VAP            37.895039
VSL            33.851009
LIN             0.438285
STR             0.878618
WOB             0.489094
BeatCross      36.868078
cluster         0.000000
dtype: float64
std
 exposure       0.000000
tracked_id    60.950767
VCL           24.815337
VAP           17.456933
VSL           17.277622
LIN            0.165236
STR            0.110792
WOB            0.152567
BeatCross      6.939272
cluster        0.000000
dtype: float64
['0', '1u']
mean
 exposure       30.000000
tracked_id    149.395939
VCL            80.325101
VAP            42.655734
VSL            38.093160
LIN             0.476626
STR             0.875451
WOB             0.532867
BeatCross      34.055538
cluster         0.000000
dtype: float64
std
 exposure        0.000000
tracked_id    101.812468
VCL            26.419879
VAP            18.799343
VSL            18.963110
LIN             0.180842
STR             0.114031
WOB             0.166030
BeatCross       6.949853
cluster         0.000000
dtype: float64
['1', '0']
mean
 exposure       30.000000
tracked_id    131.407767
VCL            91.201240
VAP            56.458394
VSL            48.332954
LIN             0.539967
STR             0.850906
WOB             0.626358
BeatCross      37.225732
cluster         1.000000
dtype: float64
std
 exposure       0.000000
tracked_id    97.719261
VCL           32.868646
VAP           20.044572
VSL           19.399941
LIN            0.150420
STR            0.132898
WOB            0.117311
BeatCross      5.771555
cluster        0.000000
dtype: float64
['1', '10n']
mean
 exposure       30.000000
tracked_id    107.161572
VCL            86.426625
VAP            51.709266
VSL            43.862527
LIN             0.507009
STR             0.838972
WOB             0.598970
BeatCross      37.472957
cluster         1.000000
dtype: float64
std
 exposure       0.000000
tracked_id    90.245062
VCL           26.860958
VAP           18.743034
VSL           18.201720
LIN            0.140550
STR            0.124904
WOB            0.117442
BeatCross      6.161093
cluster        0.000000
dtype: float64
['1', '100n']
mean
 exposure      30.000000
tracked_id    93.075812
VCL           93.194075
VAP           52.069419
VSL           42.986664
LIN            0.471176
STR            0.823320
WOB            0.565412
BeatCross     38.691018
cluster        1.000000
dtype: float64
std
 exposure       0.000000
tracked_id    56.049454
VCL           32.445777
VAP           19.533772
VSL           18.466099
LIN            0.142410
STR            0.138853
WOB            0.118639
BeatCross      5.470152
cluster        0.000000
dtype: float64
['1', '1u']
mean
 exposure       30.000000
tracked_id    126.274286
VCL            96.233651
VAP            56.062849
VSL            46.054053
LIN             0.487250
STR             0.814399
WOB             0.590200
BeatCross      37.046708
cluster         1.000000
dtype: float64
std
 exposure       0.000000
tracked_id    89.335587
VCL           35.730103
VAP           22.195557
VSL           21.402271
LIN            0.151170
STR            0.146128
WOB            0.121128
BeatCross      5.717584
cluster        0.000000
dtype: float64
['2', '0']
mean
 exposure       30.000000
tracked_id    136.944112
VCL            78.397374
VAP            43.171082
VSL            39.354099
LIN             0.496753
STR             0.898645
WOB             0.544957
BeatCross      35.976878
cluster         2.000000
dtype: float64
std
 exposure        0.000000
tracked_id    102.965008
VCL            23.537831
VAP            18.461070
VSL            18.312976
LIN             0.166917
STR             0.094606
WOB             0.155046
BeatCross       7.074417
cluster         0.000000
dtype: float64
['2', '10n']
mean
 exposure       30.000000
tracked_id    134.370370
VCL            73.302089
VAP            40.456284
VSL            37.053433
LIN             0.494510
STR             0.900843
WOB             0.541282
BeatCross      36.420001
cluster         2.000000
dtype: float64
std
 exposure       0.000000
tracked_id    99.126088
VCL           21.064100
VAP           18.651656
VSL           18.563299
LIN            0.167927
STR            0.091489
WOB            0.157150
BeatCross      6.668564
cluster        0.000000
dtype: float64
['2', '100n']
mean
 exposure       30.000000
tracked_id    109.173028
VCL            77.995046
VAP            39.510690
VSL            35.431701
LIN             0.459687
STR             0.885751
WOB             0.510867
BeatCross      36.230880
cluster         2.000000
dtype: float64
std
 exposure       0.000000
tracked_id    63.181998
VCL           26.786050
VAP           17.150302
VSL           16.804686
LIN            0.161255
STR            0.111151
WOB            0.147980
BeatCross      6.747333
cluster        0.000000
dtype: float64
['2', '1u']
mean
 exposure       30.000000
tracked_id    147.354610
VCL            79.627072
VAP            43.341796
VSL            39.310158
LIN             0.499411
STR             0.893088
WOB             0.549284
BeatCross      33.831987
cluster         2.000000
dtype: float64
std
 exposure        0.000000
tracked_id    107.929546
VCL            25.397637
VAP            18.757620
VSL            18.543595
LIN             0.181189
STR             0.097069
WOB             0.169431
BeatCross       8.193883
cluster         0.000000
dtype: float64
['3', '0']
mean
 exposure       30.000000
tracked_id    158.221545
VCL            74.156976
VAP            40.162269
VSL            36.968383
LIN             0.493770
STR             0.902263
WOB             0.537216
BeatCross      34.679858
cluster         3.000000
dtype: float64
std
 exposure        0.000000
tracked_id    102.881686
VCL            22.138738
VAP            18.843669
VSL            18.847264
LIN             0.187985
STR             0.096802
WOB             0.176715
BeatCross       6.550359
cluster         0.000000
dtype: float64
['3', '10n']
mean
 exposure       30.000000
tracked_id    150.156740
VCL            75.501201
VAP            38.664978
VSL            34.926394
LIN             0.457822
STR             0.888989
WOB             0.505418
BeatCross      35.409731
cluster         3.000000
dtype: float64
std
 exposure        0.000000
tracked_id    103.970850
VCL            22.742291
VAP            19.363211
VSL            19.104371
LIN             0.178533
STR             0.106247
WOB             0.168060
BeatCross       6.551745
cluster         0.000000
dtype: float64
['3', '100n']
mean
 exposure       30.000000
tracked_id    110.029605
VCL            73.974394
VAP            35.012950
VSL            31.051239
LIN             0.419501
STR             0.872155
WOB             0.470910
BeatCross      35.959170
cluster         3.000000
dtype: float64
std
 exposure       0.000000
tracked_id    60.373937
VCL           20.769667
VAP           15.896910
VSL           15.697462
LIN            0.168708
STR            0.114547
WOB            0.157754
BeatCross      7.040076
cluster        0.000000
dtype: float64

['3', '1u']
mean
 exposure       30.000000
tracked_id    166.289277
VCL            76.430106
VAP            39.124247
VSL            35.117732
LIN             0.457030
STR             0.878322
WOB             0.509790
BeatCross      34.039019
cluster         3.000000
dtype: float64
std
 exposure        0.000000
tracked_id    113.377758
VCL            22.558346
VAP            18.012274
VSL            18.140475
LIN             0.176121
STR             0.110699
WOB             0.164485
BeatCross       6.562930
cluster         0.000000
dtype: float64
['4', '0']
mean
 exposure       30.000000
tracked_id     97.303571
VCL           104.331143
VAP            66.260882
VSL            47.208520
LIN             0.476777
STR             0.717578
WOB             0.653166
BeatCross      39.438686
cluster         4.000000
dtype: float64
std
 exposure       0.000000
tracked_id    77.730653
VCL           36.935188
VAP           18.652535
VSL           18.001437
LIN            0.161145
STR            0.182073
WOB            0.102830
BeatCross      4.952970
cluster        0.000000
dtype: float64
['4', '10n']
mean
 exposure       30.000000
tracked_id     73.795181
VCL           108.920015
VAP            67.767782
VSL            42.849926
LIN             0.420976
STR             0.648839
WOB             0.638983
BeatCross      39.158495
cluster         4.000000
dtype: float64
std
 exposure       0.000000
tracked_id    51.981796
VCL           35.411561
VAP           17.838201
VSL           15.628241
LIN            0.158621
STR            0.195654
WOB            0.097563
BeatCross      4.792205
cluster        0.000000
dtype: float64
['4', '100n']
mean
 exposure       30.000000
tracked_id     76.765152
VCL           110.922371
VAP            66.308935
VSL            42.159433
LIN             0.398781
STR             0.646885
WOB             0.611377
BeatCross      39.987796
cluster         4.000000
dtype: float64
std
 exposure       0.000000
tracked_id    49.951210
VCL           36.152295
VAP           18.503576
VSL           16.898445
LIN            0.138488
STR            0.189382
WOB            0.088684
BeatCross      4.624869
cluster        0.000000
dtype: float64
['4', '1u']
mean
 exposure       30.000000
tracked_id    110.379009
VCL           116.031090
VAP            70.212031
VSL            46.701608
LIN             0.421732
STR             0.670162
WOB             0.621052
BeatCross      39.078226
cluster         4.000000
dtype: float64
std
 exposure       0.000000
tracked_id    77.406475
VCL           38.209532
VAP           19.145460
VSL           17.627794
LIN            0.144436
STR            0.178116
WOB            0.091804
BeatCross      4.372739
cluster        0.000000
dtype: float64
['5', '0']
mean
 exposure       30.000000
tracked_id    119.595442
VCL            89.724929
VAP            53.520419
VSL            45.079519
LIN             0.504905
STR             0.834793
WOB             0.597978
BeatCross      38.049047
cluster         5.000000
dtype: float64
std
 exposure       0.000000
tracked_id    90.057736
VCL           32.533213
VAP           21.354415
VSL           21.250667
LIN            0.150598
STR            0.156017
WOB            0.114600
BeatCross      5.815029
cluster        0.000000
dtype: float64
['5', '10n']
mean
 exposure       30.000000
tracked_id    112.719424
VCL            88.236775
VAP            51.235795
VSL            40.252701
LIN             0.466577
STR             0.790820
WOB             0.583840
BeatCross      38.241318
cluster         5.000000
dtype: float64
std
 exposure       0.000000
tracked_id    84.523428
VCL           32.058293
VAP           19.276746
VSL           18.533317
LIN            0.154379
STR            0.184236
WOB            0.108970
BeatCross      5.627644
cluster        0.000000
dtype: float64
['5', '100n']
mean
 exposure      30.000000
tracked_id    94.928775
VCL           94.908574
VAP           52.448262
VSL           40.452497
LIN            0.434971
STR            0.765385
WOB            0.560404
BeatCross     38.210210
cluster        5.000000
dtype: float64
std
 exposure       0.000000
tracked_id    57.161606
VCL           35.974257
VAP           20.449450
VSL           19.938839
LIN            0.152032
STR            0.179112
WOB            0.115207
BeatCross      5.367384
cluster        0.000000
dtype: float64
['5', '1u']
mean
 exposure       30.000000
tracked_id    140.499044
VCL           100.449683
VAP            55.974864
VSL            43.094851
LIN             0.440255
STR             0.761266
WOB             0.568138
BeatCross      37.218035
cluster         5.000000
dtype: float64
std
 exposure       0.000000
tracked_id    93.564254
VCL           40.410141
VAP           22.502625
VSL           22.202147
LIN            0.159281
STR            0.176390
WOB            0.120452
BeatCross      5.759187
cluster        0.000000
dtype: float64